import os
import yaml
import re
import requests

RULES_FILE = "rules.txt"

def fetch_yaml(url):
    try:
        r = requests.get(url, timeout=15)
        r.raise_for_status()
        return yaml.safe_load(r.text)
    except Exception as e:
        print(f"Failed to fetch {url}: {e}")
        return None

def normalize_name(name):
    name = re.sub(r'[^A-Za-z0-9_\-]', '_', name)
    return name + ".list"

def convert_rule_provider(url):
    data = fetch_yaml(url)
    if not data:
        return

    name = data.get("name", "rule")
    filename = normalize_name(name)

    rules = data.get("rules", [])

    with open(filename, "w", encoding="utf-8") as f:
        for rule in rules:
            if isinstance(rule, str):
                f.write(rule + "\n")
            elif isinstance(rule, list):
                f.write(",".join(rule) + "\n")

    print(f"Generated: {filename}")

def cleanup_old_list_files():
    for file in os.listdir("."):
        if file.endswith(".list"):
            os.remove(file)
            print(f"Removed old file: {file}")

def generate_readme():
    lists = sorted([f for f in os.listdir(".") if f.endswith(".list")])

    with open("README.md", "w", encoding="utf-8") as f:
        f.write("# QuantumultX Rule Lists\n\n")
        f.write("自动生成的 QuantumultX 规则列表：\n\n")
        for l in lists:
            f.write(f"- `{l}`\n")
        f.write(f"\n_Last update: automatically generated by GitHub Actions._\n")

def main():
    cleanup_old_list_files()

    with open(RULES_FILE, "r", encoding="utf-8") as f:
        urls = [line.strip() for line in f if line.strip()]

    for url in urls:
        convert_rule_provider(url)

    generate_readme()

if __name__ == "__main__":
    main()
